version: '2'
services:
  mysql:
    image: $IMAGE_MYSQL
    container_name: users_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456

networks:
  default:
    external:
      name: $DOCKER_NETWORK